name: RiskSphere
description: "A new Flutter project."
publish_to: 'none'
version: 6.0.0+116
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.4.0
  firebase_storage: ^12.4.10
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  flutter_autocomplete_label: ^1.0.0
  cloud_functions: ^5.1.0
  country_pickers: ^3.0.1
  phone_input:
  flutter_recaptcha_v2_compat: ^1.0.2+2
  flutter_gcaptcha_v3: ^2.0.4
  webview_flutter: ^4.5.0
  shared_preferences: ^2.5.0
  fluttertoast: ^8.2.5
  image_picker: ^1.0.8
  mat_month_picker_dialog: ^1.1.1
  easy_localization: ^3.0.6
  google_maps_flutter: ^2.9.0
  google_places_autocomplete_text_field: ^1.1.0
  uuid: ^4.4.0
  image: ^4.2.0
  cloud_firestore: ^5.4.0
  country_picker: ^2.0.26
  location: 7.0.1
  file_picker: ^8.0.0+1
  carousel_slider: ^5.0.0
  screenshot: ^3.0.0
  path_provider: ^2.1.3
  open_file: ^3.3.2
  dio: ^5.5.0+1
  collection: ^1.18.0
  flutter_typeahead: ^5.0.0
  permission_handler: ^11.3.1
  material_symbols_icons: ^4.2801.1
  flutter_speed_dial: ^7.0.0
  firebase_messaging: ^15.2.0  # Added version
  flutter_local_notifications: ^18.0.1
  markers_cluster_google_maps_flutter: ^0.1.0+2
  lottie: ^3.1.2
  data_table_2: ^2.5.15
  google_maps_cluster_manager_2: ^3.2.0
  rxdart: ^0.28.0
  async: ^2.11.0
  google_nav_bar: ^5.0.7
  remixicon: ^1.3.0
  menu_bar: ^0.5.3
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.3
  get: ^4.7.2
  dotted_border:
  timeline_tile: ^2.0.0
  flutter_screen_capture: ^1.0.1
  connectivity_plus: ^5.0.2  # Added version
  flutter_keyboard_visibility: ^6.0.0
  flutter_stripe: ^10.1.1
  tutorial_coach_mark: ^1.3.0
  external_path: ^2.2.0
  firebase_performance:
  sign_in_with_apple: ^7.0.1
  aad_oauth: ^1.0.0
  flutter_secure_storage: ^9.0.0
  syncfusion_flutter_charts: ^30.2.6+1
  marquee: ^2.3.0
  flutter_appauth: ^6.0.4
  syncfusion_flutter_pdfviewer: ^31.2.18
  fl_chart: ^1.1.1
  syncfusion_flutter_datagrid: ^31.2.2
  geocoding: ^4.0.0
  flutter_google_maps_webservices:
  geolocator: ^14.0.2
  tuple: ^2.0.2
  package_info_plus: ^9.0.0
  firebase_app_check:
  app_links:
  flutter_sharing_intent: ^2.0.4




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterfire_cli: ^1.1.0
  # Remove flutter_lints: ^2.0.0 (deprecated)

dependency_overrides:
  intl: ^0.20.2  # Add this to match flutter_localizations
  win32: ^5.5.4


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000" # adaptive icon background color


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/
    - assets/proto/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  fonts:
    - family: 'General Sans'
      fonts:
        - asset: assets/fonts/GeneralSans-Regular.otf
        - asset: assets/fonts/GeneralSans-Italic.otf
        - asset: assets/fonts/GeneralSans-Bold.otf
        - asset: assets/fonts/GeneralSans-Medium.otf
        - asset: assets/fonts/GeneralSans-Semibold.otf