import 'package:flutter/material.dart';

enum ButtonType {
  elevated,
  outlined,
  text,
  filled,
  tonal,
}

enum Screens {
  defaultScreen,
  corporateList,
  corporateAdd,
  corporateEdit,
  corporateEmployeeList,
  corporateEmployeeAdd,
  employeeList,
  employeeAdd,
  employeeEdit,
  nonCorporateList,
  connectionList,
  requestList,
  chatList,
  networkList,
  blockedList,
  //////////
  featureList,
  addFeature,
  emailSetup,
  roleList,
  roleAdd,
  verificationList,
  //////////
  corporateConnectionList,
  nonCorporateConnectionList, corporateEmployeeEdit, nonCorporateEdit,
  corporateProfile,
  /////////
  accountList,
  locationList,
  addLocation,
  generalInfo,
  securityScreen,
  teamsScreen,
  subAccountList,
  sovList,
}

enum EmailOptions {
  notifications,
  helpDesk,
  admin,
  contactUs
}


const String ThemeModeKey = 'theme_mode';

const Map<String, String> abbreviationMap = {
  'assoc': 'Association',
  'bros': 'Brothers',
  'cie': 'Compagnie',
  'co': 'Company',
  'corp': 'Corporation',
  'inc': 'Incorporated',
  'ltd': 'Limited',
  'pvt': 'Private',
};


const Map<String, String> countryPlaceholders = {
  'AD': 'XXX XXX',
  'AE': 'XXX XXX XXX',
  'AF': 'XX XXX XXXX',
  'AG': 'XXX XXXX',
  'AI': 'XXX XXXX',
  'AL': 'XX XXX XXXX',
  'AM': 'XX XXX XXX',
  'AO': 'XXX XXX XXX',
  'AQ': '1XX XXX',
  'AR': '9 XX XXXX XXXX',
  'AS': 'XXX XXXX',
  'AT': 'XXXX XXXXXX',
  'AU': '4XX XXX XXX',
  'AW': 'XXX XXXX',
  'AZ': 'XX XXX XX XX',
  'BA': 'XX XXX XXX',
  'BB': 'XXX XXXX',
  'BD': 'X XXXX XXXX',
  'BE': 'XX XX XX XX',
  'BF': 'XX XX XX XX',
  'BG': 'XX XXX XXX',
  'BH': 'XXXX XXXX',
  'BI': 'XX XX XX XX',
  'BJ': 'XX XX XX XX',
  'BL': 'XXX XXX XXX',
  'BM': 'XXX XXXX',
  'BN': 'XXX XXXX',
  'BO': 'X XXX XXXX',
  'BR': 'XX XXXXX XXXX',
  'BS': 'XXX XXXX',
  'BT': 'X XXX XXX',
  'BV': 'XXX XX XXX',
  'BW': 'XX XXX XXX',
  'BY': '(XX) XXX XX XX',
  'BZ': 'XXX XXXX',
  'CA': '(XXX) XXX-XXXX',
  'CC': 'X XXXX XXXX',
  'CD': 'XX XXX XXXX',
  'CF': 'XX XX XX XX',
  'CG': 'XX XXX XXXX',
  'CH': 'XX XXX XX XX',
  'CI': 'XX XX XX XX',
  'CK': 'XX XXX',
  'CL': '9 XXXX XXXX',
  'CM': 'XX XX XX XX',
  'CN': '1XX XXXX XXXX',
  'CO': 'XXX XXX XXXX',
  'CR': 'XXXX XXXX',
  'CU': 'X XXX XXXX',
  'CV': 'XXX XX XX',
  'CW': '9 XXX XXXX',
  'CX': '4XX XXX XXX',
  'CY': 'XX XXX XXX',
  'CZ': 'XXX XXX XXX',
  'DE': 'XXXX XXXXXXX',
  'DJ': 'XX XX XX XX',
  'DK': 'XX XX XX XX',
  'DM': 'XXX XXXX',
  'DO': 'XXX XXXX',
  'DZ': 'XX XX XX XX',
  'EC': 'XX XXX XXXX',
  'EE': 'XXXX XXXX',
  'EG': 'X XXXX XXXX',
  'EH': 'XXXX XXXXXX',
  'ER': '1 XXX XXXX',
  'ES': 'XXX XXX XXX',
  'ET': 'XX XXX XXXX',
  'FI': 'XX XXX XXXX',
  'FJ': 'XXX XXXX',
  'FK': 'XXXXX',
  'FM': 'XXX XXXX',
  'FO': 'XXXXXX',
  'FR': 'X XX XX XX XX',
  'GA': 'X XX XX XX',
  'GD': 'XXX XXXX',
  'GE': 'XXX XXX XXX',
  'GF': 'XXXXX XXXXX',
  'GG': 'XXXX XXXXXX',
  'GH': 'XX XXX XXXX',
  'GI': 'XXX XXXXX',
  'GL': 'XX XX XX',
  'GM': 'XXX XXXX',
  'GN': 'XX XX XX XX',
  'GP': 'XXX XXX XXX',
  'GQ': 'XXX XXX XXX',
  'GR': 'XXXX XXXXXX',
  'GS': 'XXXXX',
  'GT': 'X XXX XXXX',
  'GU': 'XXX XXXX',
  'GW': 'XX XX XX XX',
  'GY': 'XXX XXXX',
  'HK': 'XXXX XXXX',
  'HM': '1XX XXX',
  'HN': 'XXXX XXXX',
  'HR': 'XX XXX XXX',
  'HT': 'XX XX XX XX',
  'HU': '(1) XXX XXXX',
  'ID': 'XX XXX XXXX',
  'IE': 'XX XXX XXXX',
  'IL': 'XX XXX XXXX',
  'IM': 'XXXX XXXXXX',
  'IN': 'XXXXX XXXXX',
  'IO': 'XXX XXXX',
  'IQ': 'XXX XXX XXXX',
  'IR': 'XX XXX XXXXX',
  'IS': 'XXX XXXX',
  'IT': 'XXX XXX XXXX',
  'JE': 'XXXX XXXXXX',
  'JM': 'XXX XXXX',
  'JO': 'X XXX XXXX',
  'JP': '(X) XXXX XXXX',
  'KE': 'XXX XXXXXX',
  'KG': 'XXX XXX XXX',
  'KH': 'XX XXX XXX',
  'KI': 'XXXXX',
  'KM': 'XXX XXXX',
  'KN': 'XXX XXXX',
  'KP': 'XXX XXX XXX',
  'KR': 'XX XXXX XXXX',
  'KW': 'XXXX XXXX',
  'KY': 'XXX XXXX',
  'KZ': '7XX XXX XXXX',
  'LA': 'XX XX XXXX',
  'LB': 'X XXX XXX',
  'LC': 'XXX XXXX',
  'LI': 'XXX XXXX',
  'LK': 'XX XXX XXXX',
  'LR': 'XX XXX XXXX',
  'LS': 'XXXX XXXX',
  'LT': '(X) XXX XX XX',
  'LU': 'XXXX XXXX',
  'LV': 'XX XXX XXX',
  'LY': 'XX XXX XXXX',
  'MA': '6XX XXXXXX',
  'MC': 'XX XX XX XX',
  'MD': 'XXX XXXXX',
  'ME': 'XX XXX XXX',
  'MF': 'XXX XXX XXX',
  'MG': 'XX XX XXX XX',
  'MH': 'XXX XXXX',
  'MK': 'XX XXX XXX',
  'ML': 'XX XX XX XX',
  'MM': 'X XXXX XXXX',
  'MN': 'XX XX XXXX',
  'MO': 'XXXX XXXX',
  'MP': 'XXX XXXX',
  'MQ': 'XXX XX XX XX',
  'MR': 'XX XX XX XX',
  'MS': 'XXX XXXX',
  'MT': 'XXXX XXXX',
  'MU': 'XXXX XXXX',
  'MV': 'XXXX XXX',
  'MW': '1 XXX XXX',
  'MX': '1 XXX XXX XXXX',
  'MY': 'X-XXXX XXXX',
  'MZ': 'XX XXX XXX',
  'NA': 'XX XXX XXXX',
  'NC': 'XX.XX.XX',
  'NE': 'XX XX XX XX',
  'NF': '3XX XXX',
  'NG': 'XXX XXX XXXX',
  'NI': 'XXXX XXXX',
  'NL': 'XX XXX XXXX',
  'NO': 'XXX XX XXX',
  'NP': 'XX XXXXXX',
  'NR': 'XXX XXXX',
  'NU': 'XXXX',
  'NZ': 'XX XXX XXXX',
  'OM': 'XXXX XXXX',
  'PA': 'XXX XXXX',
  'PE': '1 XXX XXXX',
  'PF': 'XX XX XX',
  'PG': 'XXX XX XX',
  'PH': 'XX XXX XXXX',
  'PK': 'XXX XXXXXXX',
  'PL': 'XX XXX XXXX',
  'PM': 'XX XX XX',
  'PN': 'XXX XXX XXX',
  'PR': 'XXX XXXX',
  'PS': 'XXX XXX XXX',
  'PT': 'XX XXX XXXX',
  'PW': 'XXX XXXX',
  'PY': 'XXX XXX XXX',
  'QA': 'XXXX XXXX',
  'RE': 'XXX XX XX XX',
  'RO': 'XX XXX XXXX',
  'RS': 'XX XXX XXXX',
  'RU': 'XXX XXX XX XX',
  'RW': 'XXX XXX XXX',
  'SA': 'XXXX XXXXX',
  'SB': 'XXXXX',
  'SC': 'X XXX XXX',
  'SD': 'XXX XXX XXX',
  'SE': 'XX XXX XX XX',
  'SG': 'XXXX XXXX',
  'SH': 'XXXX',
  'SI': 'XX XXX XXX',
  'SJ': 'XXX XX XXX',
  'SK': 'XXX XXX XXX',
  'SL': 'XX XXX XXX',
  'SM': 'XXX XXX XXX',
  'SN': 'XX XXX XXXX',
  'SO': 'X XXX XXXX',
  'SR': 'XXX XXXX',
  'SS': 'XX XXX XXXX',
  'ST': 'XX XXXXX',
  'SV': 'XX XX XXXX',
  'SX': 'XXX XXXX',
  'SY': 'XX XXXX XXXX',
  'SZ': 'XX XX XXXX',
  'TC': 'XXX XXXX',
  'TD': 'XX XX XX XX',
  'TF': 'XXX XX XX XX',
  'TG': 'XX XX XX XX',
  'TH': 'XX XXX XXXX',
  'TJ': 'XX XXX XXXX',
  'TK': 'XXXX',
  'TL': 'XXX XXXX',
  'TM': 'XX XXXXXXX',
  'TN': 'XX XXX XXX',
  'TO': 'XXXXX',
  'TR': 'XXX XXX XXXX',
  'TT': 'XXX XXXX',
  'TV': 'XXXX',
  'TW': 'XX XXXXXXX',
  'TZ': 'XXX XXX XXX',
  'UA': 'XX XXX XX XX',
  'UG': 'XXX XXX XXX',
  'UK': 'XXXX XXXXXX',
  'UM': 'XXX XXX XXXX',
  'US': '(XXX) XXX-XXXX',
  'UY': '9X XXX XXXX',
  'UZ': 'XX XXX XX XX',
  'VA': 'XXXX XXXX',
  'VC': 'XXX XXXX',
  'VE': 'XXX-XXX XXXX',
  'VG': 'XXX XXXX',
  'VI': 'XXX XXXX',
  'VN': 'XX XXXX XXXX',
  'VU': 'XXXXX',
  'WF': 'XX XX XX',
  'WS': 'XX XXX',
  'YE': 'XXX XXX XXX',
  'YT': 'XXX XX XX XX',
  'ZA': 'XX XXX XXXX',
  'ZM': 'XXX XXX XXX',
  'ZW': 'X XXX XXX'
};

const Map<String, String> countryNameToCodeMap = {
  'Afghanistan': 'AF',
  'Albania': 'AL',
  'Algeria': 'DZ',
  'Andorra': 'AD',
  'Angola': 'AO',
  'Antigua and Barbuda': 'AG',
  'Argentina': 'AR',
  'Armenia': 'AM',
  'Australia': 'AU',
  'Austria': 'AT',
  'Azerbaijan': 'AZ',
  'Bahamas': 'BS',
  'Bahrain': 'BH',
  'Bangladesh': 'BD',
  'Barbados': 'BB',
  'Belarus': 'BY',
  'Belgium': 'BE',
  'Belize': 'BZ',
  'Benin': 'BJ',
  'Bhutan': 'BT',
  'Bolivia': 'BO',
  'Bosnia and Herzegovina': 'BA',
  'Botswana': 'BW',
  'Brazil': 'BR',
  'Brunei': 'BN',
  'Bulgaria': 'BG',
  'Burkina Faso': 'BF',
  'Burundi': 'BI',
  'Cabo Verde': 'CV',
  'Cambodia': 'KH',
  'Cameroon': 'CM',
  'Canada': 'CA',
  'Central African Republic': 'CF',
  'Chad': 'TD',
  'Chile': 'CL',
  'China': 'CN',
  'Colombia': 'CO',
  'Comoros': 'KM',
  'Congo': 'CG',
  'Congo, Democratic Republic of the': 'CD',
  'Costa Rica': 'CR',
  'Croatia': 'HR',
  'Cuba': 'CU',
  'Cyprus': 'CY',
  'Czech Republic': 'CZ',
  'Denmark': 'DK',
  'Djibouti': 'DJ',
  'Dominica': 'DM',
  'Dominican Republic': 'DO',
  'Ecuador': 'EC',
  'Egypt': 'EG',
  'El Salvador': 'SV',
  'Equatorial Guinea': 'GQ',
  'Eritrea': 'ER',
  'Estonia': 'EE',
  'Eswatini': 'SZ',
  'Ethiopia': 'ET',
  'Fiji': 'FJ',
  'Finland': 'FI',
  'France': 'FR',
  'Gabon': 'GA',
  'Gambia': 'GM',
  'Georgia': 'GE',
  'Germany': 'DE',
  'Ghana': 'GH',
  'Greece': 'GR',
  'Grenada': 'GD',
  'Guatemala': 'GT',
  'Guinea': 'GN',
  'Guinea-Bissau': 'GW',
  'Guyana': 'GY',
  'Haiti': 'HT',
  'Honduras': 'HN',
  'Hungary': 'HU',
  'Iceland': 'IS',
  'India': 'IN',
  'Indonesia': 'ID',
  'Iran': 'IR',
  'Iraq': 'IQ',
  'Ireland': 'IE',
  'Israel': 'IL',
  'Italy': 'IT',
  'Jamaica': 'JM',
  'Japan': 'JP',
  'Jordan': 'JO',
  'Kazakhstan': 'KZ',
  'Kenya': 'KE',
  'Kiribati': 'KI',
  'Korea, North': 'KP',
  'Korea, South': 'KR',
  'Kuwait': 'KW',
  'Kyrgyzstan': 'KG',
  'Laos': 'LA',
  'Latvia': 'LV',
  'Lebanon': 'LB',
  'Lesotho': 'LS',
  'Liberia': 'LR',
  'Libya': 'LY',
  'Liechtenstein': 'LI',
  'Lithuania': 'LT',
  'Luxembourg': 'LU',
  'Madagascar': 'MG',
  'Malawi': 'MW',
  'Malaysia': 'MY',
  'Maldives': 'MV',
  'Mali': 'ML',
  'Malta': 'MT',
  'Marshall Islands': 'MH',
  'Mauritania': 'MR',
  'Mauritius': 'MU',
  'Mexico': 'MX',
  'Micronesia': 'FM',
  'Moldova': 'MD',
  'Monaco': 'MC',
  'Mongolia': 'MN',
  'Montenegro': 'ME',
  'Morocco': 'MA',
  'Mozambique': 'MZ',
  'Myanmar': 'MM',
  'Namibia': 'NA',
  'Nauru': 'NR',
  'Nepal': 'NP',
  'Netherlands': 'NL',
  'New Zealand': 'NZ',
  'Nicaragua': 'NI',
  'Niger': 'NE',
  'Nigeria': 'NG',
  'North Macedonia': 'MK',
  'Norway': 'NO',
  'Oman': 'OM',
  'Pakistan': 'PK',
  'Palau': 'PW',
  'Palestine': 'PS',
  'Panama': 'PA',
  'Papua New Guinea': 'PG',
  'Paraguay': 'PY',
  'Peru': 'PE',
  'Philippines': 'PH',
  'Poland': 'PL',
  'Portugal': 'PT',
  'Qatar': 'QA',
  'Romania': 'RO',
  'Russia': 'RU',
  'Rwanda': 'RW',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  'Saint Vincent and the Grenadines': 'VC',
  'Samoa': 'WS',
  'San Marino': 'SM',
  'Sao Tome and Principe': 'ST',
  'Saudi Arabia': 'SA',
  'Senegal': 'SN',
  'Serbia': 'RS',
  'Seychelles': 'SC',
  'Sierra Leone': 'SL',
  'Singapore': 'SG',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Solomon Islands': 'SB',
  'Somalia': 'SO',
  'South Africa': 'ZA',
  'South Sudan': 'SS',
  'Spain': 'ES',
  'Sri Lanka': 'LK',
  'Sudan': 'SD',
  'Suriname': 'SR',
  'Sweden': 'SE',
  'Switzerland': 'CH',
  'Syria': 'SY',
  'Taiwan': 'TW',
  'Tajikistan': 'TJ',
  'Tanzania': 'TZ',
  'Thailand': 'TH',
  'Timor-Leste': 'TL',
  'Togo': 'TG',
  'Tonga': 'TO',
  'Trinidad and Tobago': 'TT',
  'Tunisia': 'TN',
  'Turkey': 'TR',
  'Turkmenistan': 'TM',
  'Tuvalu': 'TV',
  'Uganda': 'UG',
  'Ukraine': 'UA',
  'United Arab Emirates': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
  'Uruguay': 'UY',
  'Uzbekistan': 'UZ',
  'Vanuatu': 'VU',
  'Vatican City': 'VA',
  'Venezuela': 'VE',
  'Vietnam': 'VN',
  'Yemen': 'YE',
  'Zambia': 'ZM',
  'Zimbabwe': 'ZW',
};
