// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyi6LKiEELcYMibue6T8ecFp8XCzpvd30',
    appId: '1:160035685335:android:406df374c1134dd7a74192',
    messagingSenderId: '160035685335',
    projectId: 'project-green-r5-1-dev',
    storageBucket: 'project-green-r5-1-dev.firebasestorage.app',
  );

  /// Config for package: com.example.green

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCstV5UDSN8huvSrp738E9shu6gkltdYN8',
    appId: '1:160035685335:ios:9aec62c3a48fbf16a74192',
    messagingSenderId: '160035685335',
    projectId: 'project-green-r5-1-dev',
    storageBucket: 'project-green-r5-1-dev.firebasestorage.app',
    iosClientId: '160035685335-phveajbvmridomq1v4bj8h510ggr799f.apps.googleusercontent.com',
    iosBundleId: 'com.zerozilla.green',
  );

  /// Config for package: com.risksphere.green
  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyBVuZ3q3ztDvt6lSfwtmLzttJmI6WKxTy4',
  //   appId: '1:37861143894:android:3f15059cd05d48e1bd12f7',
  //   messagingSenderId: '37861143894',
  //   projectId: 'project-green-f4d78',
  //   databaseURL: 'https://project-green-f4d78-default-rtdb.firebaseio.com',
  //   storageBucket: 'project-green-f4d78.firebasestorage.app',
  // );
  //
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAMSQEI5O6EXj1SgdU4YA25KIaEeu5uv-o',
  //   appId: '1:37861143894:ios:5b6ce902afab71b5bd12f7',
  //   messagingSenderId: '37861143894',
  //   projectId: 'project-green-f4d78',
  //   databaseURL: 'https://project-green-f4d78-default-rtdb.firebaseio.com',
  //   storageBucket: 'project-green-f4d78.firebasestorage.app',
  //   androidClientId: '37861143894-n9cr0a2g3d38sv2uothhaffhl43dhgda.apps.googleusercontent.com',
  //   iosClientId: '37861143894-bjhuqbmhiup2i290no49ra2d4ld6qdfb.apps.googleusercontent.com',
  //   iosBundleId: 'com.zerozilla.green',
  // );

// apiKey: "AIzaSyCYkVSSfxlq0G0URowvvyfq7Pn1Af_f2YA",
// authDomain: "project-green-r5-1-qa.firebaseapp.com",
// projectId: "project-green-r5-1-qa",
// storageBucket: "project-green-r5-1-qa.firebasestorage.app",
// messagingSenderId: "857135835532",
// appId: "1:857135835532:web:921d30d6259ce18ac84ea9"
}