
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
static FirebaseOptions get currentPlatform {
if (kIsWeb) {
throw UnsupportedError(
'DefaultFirebaseOptions have not been configured for web - '
'you can reconfigure this by running the FlutterFire CLI again.',
);
}
switch (defaultTargetPlatform) {
case TargetPlatform.android:
return android;
case TargetPlatform.iOS:
return ios;
case TargetPlatform.macOS:
throw UnsupportedError(
'DefaultFirebaseOptions have not been configured for macos - '
'you can reconfigure this by running the FlutterFire CLI again.',
);
case TargetPlatform.windows:
throw UnsupportedError(
'DefaultFirebaseOptions have not been configured for windows - '
'you can reconfigure this by running the FlutterFire CLI again.',
);
case TargetPlatform.linux:
throw UnsupportedError(
'DefaultFirebaseOptions have not been configured for linux - '
'you can reconfigure this by running the FlutterFire CLI again.',
);
default:
throw UnsupportedError(
'DefaultFirebaseOptions are not supported for this platform.',
);
}
}

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1bCXCsBjWxXrG7Dd9dN7DaQoYmebfO8Q',
    appId: '1:781106067514:android:b65e4a2260608981009d03',
    messagingSenderId: '781106067514',
    projectId: 'project-green-dev-429104',
    databaseURL: 'https://project-green-dev-429104-default-rtdb.firebaseio.com',
    storageBucket: 'project-green-dev-429104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-dUbaXycqAOpPZzQSaQ3mkSLXyhadE0',
    appId: '1:781106067514:ios:d988e7e8e0e1d6c0009d03',
    messagingSenderId: '781106067514',
    projectId: 'project-green-dev-429104',
    databaseURL: 'https://project-green-dev-429104-default-rtdb.firebaseio.com',
    storageBucket: 'project-green-dev-429104.appspot.com',
    androidClientId: '781106067514-cr2tvf2i0952rfnpnaleb25l449qa59r.apps.googleusercontent.com',
    iosClientId: '781106067514-vg3tqt2m694h0qd3enl4toff2eug19cp.apps.googleusercontent.com',
    iosBundleId: 'com.zerozilla.green',
  );

}