// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP-LLpikZbtQIa4e7KfkMlwoIXvRuQQGw',
    appId: '1:733517635954:android:24b7f1816d68861d3e7deb',
    messagingSenderId: '733517635954',
    projectId: 'risksphere-qa',
    storageBucket: 'risksphere-qa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-LLpikZbtQIa4e7KfkMlwoIXvRuQQGw',
    appId: '1:733517635954:ios:a414de0cd681c5353e7deb',
    messagingSenderId: '733517635954',
    projectId: 'risksphere-qa',
    storageBucket: 'risksphere-qa.firebasestorage.app',
    iosClientId:
        '733517635954-u4fmh34dev6cf28ak18hp573djle1h0n.apps.googleusercontent.com',
    iosBundleId: 'com.sonofthunder.risksphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWLlgn4SYw-8aHdPLfeylQ78AsUqyCvv4',
    appId: '1:863607711683:web:447afcd446ce53cabcff76',
    messagingSenderId: '863607711683',
    projectId: 'project-green-prod',
    authDomain: 'project-green-prod.firebaseapp.com',
    storageBucket: 'project-green-prod.firebasestorage.app',
  );
}
